###login
post http://localhost:3000/api/users/login
Content-Type: application/json

{
    "Email": "kisadmin@gmail.com",
    "Password": "admin"
}

### registration
post http://localhost:3000/api/users/registration
Content-Type: application/json

{
     "FirstName": "teszt",
     "LastName": "vendeg",
     "Email": "vendeg@gmail.com",
     "Password": "vendeg",
     "PhoneNumber": "06502350",
     "Permission": "1"
}

### Userek
get http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjksImZpcnN0TmFtZSI6IkxldmVudGUiLCJsYXN0TmFtZSI6IkbDvGxlIiwiZ2VuZGVyIjoiZsOpcmZpIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjA2MzAxMjM0NTM1IiwicGVybWlzc2lvbiI6MX0sImlhdCI6MTY0Njc0MzQwNiwiZXhwIjoxNjQ2NzQ3MDA2fQ.Y38yW1pX655_gj3oBbTIpVcVj8uItTOFz3xssKiEMQ8


### Egy user
get http://localhost:3000/api/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NDMxNTE5NCwiZXhwIjoxNjQ0MzE4Nzk0fQ.q2ih8UiVs51Pa3UEc908O6tLt5Upl9NOlidEmQSksMQ



### User módosítása
put http://localhost:3000/api/users
Content-Type: application/json

{
    "FirstName": "kis",
    "LastName": "admin",
    "Email": "kisadmin@gmail.com",
    "Password": "admin",
    "PhoneNumber":"06304512350",
    "Permission": ,
    "id": 4
}

### Delete user
delete http://localhost:3000/api/users
Content-Type: application/json

{
    "id": 1
}


#category


### create categorys
post http://localhost:3000/api/users/category
Content-Type: application/json

{
     "CategoryName": "Pálinka"
}

### get categorys
get http://localhost:3000/api/users/category/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NTEyNTYzOCwiZXhwIjoxNjQ1MTI5MjM4fQ.62U_xM_tXvohkZ1TlZqxSLLil5Y1dTbfmPgB2JYUlsQ


### Egy category
get http://localhost:3000/api/users/category/categories/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NTQ0NjI3MiwiZXhwIjoxNjQ1NDQ5ODcyfQ.mt6Ga598tVLQ3QXty4BF-amaU2Jbaww4U5z5AaUXvsg


### category módosítása
put http://localhost:3000/api/users/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NTEyNTYzOCwiZXhwIjoxNjQ1MTI5MjM4fQ.62U_xM_tXvohkZ1TlZqxSLLil5Y1dTbfmPgB2JYUlsQ

{
    "CategoryName": "Pálinka",
    "id": 1
}

### Delete category
delete http://localhost:3000/api/users/category
Content-Type: application/json

{
    "id": 15
}

### Items hozzáadása
post http://localhost:3000/api/users/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NTQ0NjI3MiwiZXhwIjoxNjQ1NDQ5ODcyfQ.mt6Ga598tVLQ3QXty4BF-amaU2Jbaww4U5z5AaUXvsg

{ 
    "CategoryId": 1, 
    "ItemName": "árpád alma pálinka", 
    "Image": "https://www.google.com/search?q=%C3%A1rp%C3%A1d+alma+p%C3%A1linka&hl=hu&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiz_4u1obb2AhWQyqQKHebKBWcQ_AUoAXoECAEQAw&biw=1920&bih=979&dpr=1#imgrc=vRdWbTfQ_OAhSM",
    "Unit": "0.5L",
    "Alcoholcontent": 40,
    "Brand": "Árpád Pálinka"

 }

### get items
get http://localhost:3000/api/users/items/itemList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NTQ0NjI3MiwiZXhwIjoxNjQ1NDQ5ODcyfQ.mt6Ga598tVLQ3QXty4BF-amaU2Jbaww4U5z5AaUXvsg

### Egy Item
get http://localhost:3000/api/users/items/itemList/6
Authorization: Bearer

### item módosítása
put http://localhost:3000/api/users/items
Content-Type: application/json

{
    "CategoryId": 1,
    "ItemName": "árpád körte pálink",
    "Image": "https://www.kozertplusz.hu/wp-content/uploads/2021/09/Arpad-Silver-Vilmoskorte-1800x1800.jpg",
    "Unit": "0.5L",
    "Alcoholcontent": 40,
    "Brand":"Árpád Pálinka",
    "id": 3
}

### Delete item
delete http://localhost:3000/api/users/items
Content-Type: application/json

{
    "id": 6
}

### Item prices hozzáadása
post http://localhost:3000/api/users/itemprices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NTQ0NjI3MiwiZXhwIjoxNjQ1NDQ5ODcyfQ.mt6Ga598tVLQ3QXty4BF-amaU2Jbaww4U5z5AaUXvsg

{ 
    "ItemId": 8, 
    "Date": "2022-03-25 08:27:35", 
    "Price": "7999"
}

### get itemprices
get http://localhost:3000/api/users/items/itemprices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NTEyNTYzOCwiZXhwIjoxNjQ1MTI5MjM4fQ.62U_xM_tXvohkZ1TlZqxSLLil5Y1dTbfmPgB2JYUlsQ

### Egy itemprice
get http://localhost:3000/api/users/items/itemprices/2"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NDMxNTE5NCwiZXhwIjoxNjQ0MzE4Nzk0fQ.q2ih8UiVs51Pa3UEc908O6tLt5Upl9NOlidEmQSksMQ

### price módosítása
put http://localhost:3000/api/users/items/itemprices
Content-Type: application/json

{
    "ItemId": 1,
    "Date": "2022-03-25",
    "Price": "9998",
    "id": 2
}

### Delete itemprice
delete http://localhost:3000/api/users/itemprices
Content-Type: application/json

{
    "id": 6
}

### userrating hozzáadása
post http://localhost:3000/api/users/userrating
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NTQ0NjI3MiwiZXhwIjoxNjQ1NDQ5ODcyfQ.mt6Ga598tVLQ3QXty4BF-amaU2Jbaww4U5z5AaUXvsg

{ 
    "UserId": 1, 
    "Comment": "Ez szar", 
    "Rating": 2,
    "ItemId": 5
 }

### get userratings
get http://localhost:3000/api/users/items/userrating
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NTEyNTYzOCwiZXhwIjoxNjQ1MTI5MjM4fQ.62U_xM_tXvohkZ1TlZqxSLLil5Y1dTbfmPgB2JYUlsQ

### Egy userrating
get http://localhost:3000/api/users/items/userrating/2"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NDMxNTE5NCwiZXhwIjoxNjQ0MzE4Nzk0fQ.q2ih8UiVs51Pa3UEc908O6tLt5Upl9NOlidEmQSksMQ

### userrating módosítása
put http://localhost:3000/api/users/items/userrating
Content-Type: application/json

{
    "UserId": 1,
    "Comment": "Ez nagyon jó",
    "Rating": 10,
    "ItemId": 2,
    "id": 2
}

### Delete userrating
delete http://localhost:3000/api/users/items/userrating
Content-Type: application/json

{
    "id": 1
}